export { default as CustomerPage } from './CustomerPage'
export { default as MenuPage } from './MenuPage'
export { default as CartPage } from './CartPage'
export { default as OrdersPage } from './OrdersPage'
export { default as OrderDetailPage } from './OrderDetailPage'
export { default as PaymentPage } from './PaymentPage'
export { default as CallStaffPage } from './CallStaffPage'
